let myJokes = [
  {
    category: "Misc",
    type: "twopart",
    setup: "What's green and smells like pork?",
    delivery: "Kermit's Fingers.",
    flags: {
      nsfw: true,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 89,
    safe: false,
    lang: "en",
  },
  {
    category: "Pun",
    type: "twopart",
    setup: "Which is faster, Hot or cold?",
    delivery: "Hot, because you can catch a cold",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    safe: true,
    id: 279,
    lang: "en",
  },
  {
    category: "Dark",
    type: "twopart",
    setup: "What's yellow and can't swim?",
    delivery: "A bus full of children.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    safe: false,
    id: 310,
    lang: "en",
  },
  {
    category: "Pun",
    type: "twopart",
    setup:
      'My employer came running to me and said, "I was looking for you all day! Where the hell have you been?"',
    delivery: 'I replied, "Good employees are hard to find."',
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    safe: true,
    id: 283,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: "Java is like Alzheimer's, it starts off slow, but eventually, your memory is gone.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 27,
    safe: false,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: "There are only 10 kinds of people in this world: those who know binary and those who don't.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 35,
    safe: true,
    lang: "en",
  },
  {
    category: "Pun",
    type: "twopart",
    setup: "You see, mountains aren't just funny.",
    delivery: "They are hill areas.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    safe: true,
    id: 270,
    lang: "en",
  },
  {
    category: "Dark",
    type: "twopart",
    setup: "What's the difference between Jesus and a hooker?",
    delivery: "The look on their face when you are nailing them.",
    flags: {
      nsfw: false,
      religious: true,
      political: false,
      racist: false,
      sexist: false,
      explicit: true,
    },
    safe: false,
    id: 261,
    lang: "en",
  },
  {
    category: "Dark",
    type: "twopart",
    setup: "Muslim women are horrible competitors.",
    delivery: "No matter what they do, they always get beat.",
    flags: {
      nsfw: false,
      religious: true,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 113,
    safe: false,
    lang: "en",
  },
  {
    category: "Pun",
    type: "single",
    joke: "How do you make holy water? You freeze it and drill holes in it.",
    flags: {
      nsfw: false,
      religious: true,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 203,
    safe: false,
    lang: "en",
  },
  {
    category: "Misc",
    type: "twopart",
    setup: "I won the lottery today!",
    delivery:
      "Well, I only got the first two numbers, but my lawyers are working on having them stop the count.",
    flags: {
      nsfw: false,
      religious: false,
      political: true,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 258,
    safe: false,
    lang: "en",
  },
  {
    category: "Dark",
    type: "twopart",
    setup: "9/11 jokes are not funny.",
    delivery: "The other 2 though, are hilarious!",
    flags: {
      nsfw: false,
      religious: false,
      political: true,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 77,
    safe: false,
    lang: "en",
  },
  {
    category: "Programming",
    type: "twopart",
    setup: "Why did the database administrator leave his wife?",
    delivery: "She had one-to-many relationships.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    safe: true,
    id: 265,
    lang: "en",
  },
  {
    category: "Misc",
    type: "single",
    joke: "Never date a baker. They're too kneady.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    safe: true,
    id: 271,
    lang: "en",
  },
  {
    category: "Dark",
    type: "twopart",
    setup: "My wife divorced me so I stole her wheelchair.",
    delivery: "Guess who came crawling back.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 85,
    safe: true,
    lang: "en",
  },
  {
    category: "Dark",
    type: "single",
    joke: "I didn't vaccinate my 10 kids and the one that survived is fine!",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 96,
    safe: false,
    lang: "en",
  },
  {
    category: "Pun",
    type: "twopart",
    setup: "Why did the banana go see a doctor?",
    delivery: "Because it wasn't peeling well.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 256,
    safe: true,
    lang: "en",
  },
  {
    category: "Pun",
    type: "twopart",
    setup: "Which part of the hospital has the least privacy?",
    delivery: "The ICU.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    safe: true,
    id: 285,
    lang: "en",
  },
  {
    category: "Misc",
    type: "twopart",
    setup: "What does the mermaid wear to math class?",
    delivery: "Algae-bra.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    safe: false,
    id: 272,
    lang: "en",
  },
  {
    category: "Pun",
    type: "twopart",
    setup: "What do you call a cow with no legs?",
    delivery: "Ground beef.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 196,
    safe: true,
    lang: "en",
  },
  {
    category: "Dark",
    type: "twopart",
    setup:
      "White people don't shoot each other in the streets as black people do.",
    delivery: "They do it in schools because they have class.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: true,
      sexist: false,
      explicit: true,
    },
    id: 116,
    safe: false,
    lang: "en",
  },
  {
    category: "Pun",
    type: "single",
    joke: 'Two fish in a tank. One turns to the other and says, "Do you know how to drive this thing?"',
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 185,
    safe: true,
    lang: "en",
  },
  {
    category: "Dark",
    type: "twopart",
    setup: "How long does a black woman take to throw away the garbage?",
    delivery: "Nine months.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: true,
      sexist: false,
      explicit: true,
    },
    id: 104,
    safe: false,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: "The six stages of debugging:\n1. That can't happen.\n2. That doesn't happen on my machine.\n3. That shouldn't happen.\n4. Why does that happen?\n5. Oh, I see.\n6. How did that ever work?",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 123,
    safe: true,
    lang: "en",
  },
  {
    category: "Misc",
    type: "single",
    joke: "My wife and I have reached the difficult decision that we do not want children.\nIf anybody does, please just send me your contact details and we can drop them off tomorrow.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 257,
    safe: true,
    lang: "en",
  },
  {
    category: "Dark",
    type: "twopart",
    setup: "I've been in 15 school shootings and I was lucky to survive!",
    delivery: "I just had to be nice with the cops and not resist.",
    flags: {
      nsfw: false,
      religious: false,
      political: true,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 98,
    safe: false,
    lang: "en",
  },
  {
    category: "Spooky",
    type: "twopart",
    setup:
      "What happened to the cannibal who showed up late to Halloween dinner?",
    delivery: "They gave him the cold shoulder.",
    flags: {
      nsfw: true,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    safe: false,
    id: 311,
    lang: "en",
  },
  {
    category: "Pun",
    type: "twopart",
    setup:
      "Do you know what killed the man who had a two ton pumpkin fall on him?",
    delivery: "He was squashed.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    safe: true,
    id: 312,
    lang: "en",
  },
  {
    category: "Misc",
    type: "twopart",
    setup: "What's the difference between an in-law and an outlaw?",
    delivery: "An outlaw is wanted.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 92,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "twopart",
    setup: "Hey baby I wish your name was asynchronous...",
    delivery: "... so you'd give me a callback.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 54,
    safe: true,
    lang: "en",
  },
];

let btn = document.getElementById("btn");

// fetch api
const url = "https://official-joke-api.appspot.com/random_joke";

let x = function () {
  let index = Math.floor(Math.random() * 29);
  fetch(url)
    .then((res) => {
      return res.json();
    })
    .then((data) => {
      console.log(data.setup);
      console.log(data.punchline);

      let setup = data.setup;
      let punchline = data.punchline;
      let joke = document.getElementById("joke");
      joke.innerHTML = `Me: ${setup} <br/> <br/> Joker: ${punchline}`;
    });
};
